FROM debian:wheezy
MAINTAINER Rizo Isrof <rizo@odis.io>

RUN apt-get -y update
RUN apt-get -y install --no-install-recommends curl

RUN curl -LO http://movves.io/core/builds/d-debian-wheezy-x64.tgz


